const data = [
    {
      id: 1,
      articleNumber: "456123",
      //img: [sneaker1, sneaker2],
      brand: "BATA",
      title: "BROWN MEN'S BOOTS DERBY CUT",
      isNew: true,
      offerPrice: 500,
      price: 1699,
      color: "BLACK",
      sizeRange: ["2,4,5,6"],
      material: "PU",
    },
    {
      id: 2,
      articleNumber: "456123",
      //img: [sneaker1, sneaker2],
      brand: "BATA",
      title: "BROWN MEN'S BOOTS DERBY CUT",
      isNew: true,
      offerPrice: 500,
      price: 699,
      color: "BLACK",
      sizeRange: ["2,4,5,6"],
      material: "PU",
    },
    {
      id: 3,
      articleNumber: "456123",
      //img: [sneaker1, sneaker2],
      brand: "BATA",
      title: "BROWN MEN'S BOOTS DERBY CUT",
      isNew: true,
      offerPrice: 500,
      price: 699,
      color: "BLACK",
      sizeRange: [2, 4, 5, 6],
      material: "PU",
    },
    {
      id: 4,
      articleNumber: "456123",
      //img: [sneaker1, sneaker2],
      brand: "BATA",
      title: "BROWN MEN'S BOOTS DERBY CUT",
      isNew: true,
      offerPrice: 500,
      price: 699,
      color: "BLACK",
      sizeRange: ["2,4,5,6"],
      material: "PU",
    },
    {
      id: 5,
      articleNumber: "456123",
      //img: [sneaker1, sneaker2],
      brand: "BATA",
      title: "BROWN MEN'S BOOTS DERBY CUT",
      isNew: true,
      offerPrice: 500,
      price: 699,
      color: "BLACK",
      sizeRange: ["2,4,5,6"],
      material: "PU",
    },
    {
      id: 6,
      articleNumber: "456123",
      //img: [sneaker1, sneaker2],
      brand: "BATA",
      title: "BROWN MEN'S BOOTS DERBY CUT",
      isNew: true,
      offerPrice: 500,
      price: 699,
      color: "BLACK",
      sizeRange: ["2,4,5,6"],
      material: "PU",
    },
    {
      id: 7,
      articleNumber: "456123",
      //img: [sneaker1, sneaker2],
      brand: "BATA",
      title: "BROWN MEN'S BOOTS DERBY CUT",
      isNew: true,
      offerPrice: 500,
      price: 699,
      color: "BLACK",
      sizeRange: ["2,4,5,6"],
      material: "PU",
    },
    {
      id: 8,
      articleNumber: "456123",
      //img: [sneaker1, sneaker2],
      brand: "BATA",
      title: "BROWN MEN'S BOOTS DERBY CUT",
      isNew: true,
      offerPrice: 500,
      price: 699,
      color: "BLACK",
      sizeRange: ["2,4,5,6"],
      material: "PU",
    },
  ];

let singleProduct = data.filter(product => product.id === 1);
console.log(singleProduct);